#!/usr/bin/env bash

CONFIG_DIR=~/.config/beamlynx
CONFIG_FILE=$CONFIG_DIR/config
TMP_DIR=/tmp/beamlynx

cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%d %H:%M:%S")
  echo " :: $timestamp :: [$script_name] ::  $1"
}
