#!/usr/bin/env bash
set -e
export WORKDIR=$(cd "$(dirname "$(realpath "$0")")" && pwd)
. "$WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo -e "
\033[90m
  $cli_name
  Beamlynx Command Line Interface
  Version: $(cat $WORKDIR/VERSION)
  https://github.com/pine-lang/pine-cli
`cat $WORKDIR/art/logo.txt`

Usage: $cli_name [command]

Commands:
  api           Run the pine-lang server
  ui            Run beamlynx
  config        See the configuration i.e. database connections etc.
  *             Help

\033[0m
"
  exit 0
}

main () {
    case "$1" in
        ui)
            "$WORKDIR/commands/app" | tee -ia "$WORKDIR/logs/app.log"
            ;;
        api)
            "$WORKDIR/commands/server" $3 | tee -ia "$WORKDIR/logs/server.log"
            ;;

        config)
            "$WORKDIR/commands/config"
            ;;
        update)
            "$WORKDIR/commands/update" "$1" | tee -ia "$WORKDIR/logs/update.log"
            ;;
        *)
            cli_help
            ;;
    esac

}
main "$@"
